"""initial schema with sheet embeddings

Revision ID: c645be70bf3d
Revises: 
Create Date: 2026-03-17 12:54:11.047037

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from pgvector.sqlalchemy import Vector


# revision identifiers, used by Alembic.
revision: str = 'c645be70bf3d'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('sheet_embeddings',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('workbook_id', sa.Integer(), nullable=False),
    sa.Column('sheet_name', sa.String(length=255), nullable=False),
    sa.Column('table_name', sa.String(length=255), nullable=False),
    sa.Column('description', sa.Text(), nullable=False),
    sa.Column('embedding', Vector(1536), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['workbook_id'], ['workbooks.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_sheet_embeddings_workbook_id'), 'sheet_embeddings', ['workbook_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_sheet_embeddings_workbook_id'), table_name='sheet_embeddings')
    op.drop_table('sheet_embeddings')
    # ### end Alembic commands ###
